#!/bin/bash

# sed -e '1d' RVTools_tabvNetwork.csv > probe
# rm -rf RVTools_tabvNetwork.csv
# mv probe RVTools_tabvNetwork.csv

# First of all you must rewrite RVtools_tabvNewtwork.csv as UTF-8
# Then you need to uncoment fisrt three lines in this file if you run this first time
# After that run this script.

# This part creates file for import VM Objects

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1 > 1
awk '{print $0 ";"}' 1 > 2
awk '{print $0 $0}' 2 > 3
awk '{print "OBJECT;VM;"$0}' 3 > 4
rev 4 | cut -c 2- | rev > Racktables_import_Objects_new
rm -rf [1-4]

# This part creates file for import VM Objects IPs

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,11 | grep -v unknown | tr ' ' ';' | cut -d ';' -f 1,6 | grep -v fe80 | grep ';' | grep -v .169 >> 1
cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,11 | grep -v unknown | tr ' ' ';' | cut -d ';' -f 1,5 | grep -v fe80 | grep ';' | grep -v .169 >> 1 
cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,11 | grep -v unknown | tr ' ' ';' | cut -d ';' -f 1,4 | grep -v fe80 | grep ';' | grep -v .169 >> 1
cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,11 | grep -v unknown | tr ' ' ';' | cut -d ';' -f 1,3 | grep -v fe80 | grep ';' | grep -v .169 >> 1
cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,11 | grep -v unknown | tr ' ' ';' | cut -d ';' -f 1,2 | grep -v fe80 | grep ';' | grep -v .169 >> 1
sed -i 's/;/;eth0;/g' 1
awk '{print "OBJECTIP;"$0}' 1 > 2 
awk '{print $0";regular"}' 2 > Racktables_import_ObjectsIP_new
sed -i 's/,;/;/g' Racktables_import_ObjectsIP_new
rm -rf [1,2]

#  This part creates file for import Object Names

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,14 | grep -v '; ' > 1 
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10020;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Names
rm -rf [1-4]

# This part creates file for import Object Enviroment

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,15 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10021;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Env
rm -rf [1-4]

# This part creates file for import Object Creation Date

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,16 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10022;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_CreationDate
rm -rf [1-4]

# This part creates file for import Object Creation Cause

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,17 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10023;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Creation_cause
rm -rf [1-4]

# This part creates file for import info Who create this Objects

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,18 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10024;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Who_create
rm -rf [1-4]

# This part creates file for Objects Locations

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,19 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10025;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Location
rm -rf [1-4]

# This part creates file for import info about Subdivisions

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,21 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10027;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Subdivison
rm -rf [1-4]

# This part creates file for import info about Responsible Persons

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,22 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10028;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_ResponsiblePerson
rm -rf [1-4]

# This part creaters file about Conctractors

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,23 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10029;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Contractor
rm -rf [1-4]

# This part creates file about Resposible Contractors

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,24 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10030;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_ResponsibleContractor
rm -rf [1-4]

# This part creates file about Objects Funcions

cat RVTools_tabvNetwork.csv | cut -d ';' -f 1,25 | grep -v '; ' > 1
sed '/;$/d' 1 > 2
sed '/"$/d' 2 > 3
sed -i 's/;/;10031;/g' 3
awk '{print "OBJECTATTRIBUTE;"$0}' 3 > 4
cat 4 | grep -v 'Veeam Backup:' > Object_Function
rm -rf [1-4]

# You can uncomment this strings if you want to import data in one file
cat Racktables_import* >> import
cat Object_* >> import
rm -rf Rack*
rm -rf Object*


echo _________________________________________________________________________
echo SCRIPT COMPLETED
echo -------------------------------------------------------------------------
